name:  "TSmart_test"
description:  "UDP based control of the T-Smart water heater thermostats"
version:  "0.9"
image: zenfarion/tsmart
slug:  "tsmart_test"
init:  true
map:
  - config:rw
boot:  auto
url:  https://github.com/zenfarion/tsmart
legacy:  true
arch: 
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  IP_Address: "192.168.1.123"
  self_run_timer: 10
  Log_Level: "Error"
  Debug_File_Location: ""
  MQTT_Output: True
  MQTT_Address: "core-mosquitto"
  MQTT_Username: ""
  MQTT_Password: ""
  MQTT_Topic: "TSmart"
  MQTT_Port: 1883
  ha_device_prefix: "TSmart"
schema: 
  IP_Address: str
  self_run_timer: int
  Log_Level: str
  Debug_File_Location: "str?"
  MQTT_Output: bool
  MQTT_Address: "str"
  MQTT_Username: "str?"
  MQTT_Password: "str?"
  MQTT_Topic: "str?"
  MQTT_Port: int
  ha_device_prefix: "str?"
