version: '3'
services:
  tsmart_test:
    container_name: TSmart_test
    image: zenfarion/tsmart
    restart: unless-stopped
    environment:
      - IP_Address=xx.xx.xx.xx
      - MQTT_Address=xx.xx.xx.xx
      - self_run_timer=60
    network_mode: host
